# Generated by Django 4.2 on 2026-06-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('chien', 'Chien'), ('chat', 'Chat'), ('lapin', 'Lapin'), ('autre', 'Autre')], max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Âge en années')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('adopte', 'Adopté'), ('en_soin', 'En soin')], default='disponible', max_length=20)),
                ('photo_url', models.URLField(blank=True)),
                ('adoption_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
